// src/lib/foodData.js

export const foodCategories = [
  { id: 'all', name: '全部', nameEn: 'All', icon: '🍽️', order: 0 },
  {
    id: 'nightmarket',
    name: '青云夜市',
    nameEn: 'Night Market',
    icon: '🌙',
    order: 1,
  },
  { id: 'luosifen', name: '螺蛳粉', nameEn: 'Luosifen', icon: '🍜', order: 2 },
  {
    id: 'giftbox',
    name: '特产礼盒',
    nameEn: 'Gift Boxes',
    icon: '🎁',
    order: 3,
  },
  { id: 'drinks', name: '特色饮品', nameEn: 'Drinks', icon: '🥤', order: 4 },
  {
    id: 'delivery',
    name: '外卖配送',
    nameEn: 'Delivery',
    icon: '🚚',
    order: 5,
  },
];

export const foodProducts = [
  // ========== 青云夜市 (Night Market) - 7 items ==========
  {
    id: 1,
    name: '青云烤串',
    nameEn: 'Qingyun BBQ Skewers',
    category: 'nightmarket',
    price: 15,
    originalPrice: 20,
    unit: '串',
    imageUrl: 'https://i.imgur.com/SSlCA9P.jpeg',
    placeholderImage: '🍢',
    seller: '青云夜市A区',
    sellerId: 'seller_001',
    rating: 4.8,
    reviewCount: 234,
    stock: 999,
    deliveryType: 'local',
    description: '炭火烤制，秘制酱料',
    tags: ['烧烤', '夜市', '热门'],
  },
  {
    id: 2,
    name: '柳州炒螺',
    nameEn: 'Liuzhou Fried Snails',
    category: 'nightmarket',
    price: 25,
    originalPrice: 30,
    unit: '份',
    imageUrl: 'https://i.imgur.com/ipk92lv.jpeg',
    placeholderImage: '🐚',
    seller: '青云老字号',
    sellerId: 'seller_002',
    rating: 4.7,
    reviewCount: 189,
    stock: 500,
    deliveryType: 'local',
    description: '香辣入味，下酒好菜',
    tags: ['螺类', '下酒菜', '特色'],
  },
  {
    id: 3,
    name: '烤生蚝',
    nameEn: 'Grilled Oysters',
    category: 'nightmarket',
    price: 30,
    originalPrice: 45,
    unit: '6只',
    imageUrl: 'https://i.imgur.com/mc0jOK7.jpeg',
    placeholderImage: '🦪',
    seller: '青云海鲜档',
    sellerId: 'seller_003',
    rating: 4.9,
    reviewCount: 456,
    stock: 300,
    deliveryType: 'local',
    description: '蒜蓉烤生蚝，新鲜肥美',
    tags: ['海鲜', '烧烤', '必吃'],
  },
  {
    id: 4,
    name: '青云豆腐花',
    nameEn: 'Qingyun Tofu Pudding',
    category: 'nightmarket',
    price: 8,
    originalPrice: 12,
    unit: '碗',
    imageUrl: 'https://i.imgur.com/GgGZHC3.jpeg',
    placeholderImage: '🥣',
    seller: '青云甜品店',
    sellerId: 'seller_004',
    rating: 4.6,
    reviewCount: 167,
    stock: 999,
    deliveryType: 'local',
    description: '甜咸可选，滑嫩可口',
    tags: ['甜品', '夜市', '老少皆宜'],
  },
  {
    id: 14,
    name: '烤茄子',
    nameEn: 'Grilled Eggplant',
    category: 'nightmarket',
    price: 12,
    originalPrice: 18,
    unit: '份',
    imageUrl: 'https://i.imgur.com/aFCBq7p.jpeg',
    placeholderImage: '🍆',
    seller: '青云烧烤档',
    sellerId: 'seller_005',
    rating: 4.5,
    reviewCount: 89,
    stock: 500,
    deliveryType: 'local',
    description: '蒜蓉烤茄子，软糯入味',
    tags: ['烧烤', '素食'],
  },
  {
    id: 15,
    name: '炒田螺',
    nameEn: 'Stir-fried River Snails',
    category: 'nightmarket',
    price: 28,
    originalPrice: 38,
    unit: '份',
    imageUrl: 'https://i.imgur.com/NIVy2T9.jpeg',
    placeholderImage: '🐌',
    seller: '青云螺味馆',
    sellerId: 'seller_006',
    rating: 4.7,
    reviewCount: 145,
    stock: 400,
    deliveryType: 'local',
    description: '紫苏炒田螺，香辣鲜美',
    tags: ['螺类', '下酒菜'],
  },
  {
    id: 23,
    name: '铁板鱿鱼',
    nameEn: 'Teppanyaki Squid',
    category: 'nightmarket',
    price: 20,
    originalPrice: 28,
    unit: '份',
    imageUrl: 'https://i.imgur.com/mT8rzQP.jpeg',
    placeholderImage: '🦑',
    seller: '青云铁板烧',
    sellerId: 'seller_007',
    rating: 4.8,
    reviewCount: 234,
    stock: 300,
    deliveryType: 'local',
    description: '铁板鱿鱼，Q弹入味',
    tags: ['铁板烧', '海鲜'],
  },

  // ========== 螺蛳粉 (Luosifen) - 5 items ==========
  {
    id: 5,
    name: '现煮螺蛳粉',
    nameEn: 'Fresh Luosifen',
    category: 'luosifen',
    price: 18,
    originalPrice: 25,
    unit: '碗',
    imageUrl: 'https://i.imgur.com/o00XI2u.jpeg',
    placeholderImage: '🍜',
    seller: '青云螺蛳粉总店',
    sellerId: 'seller_008',
    rating: 4.9,
    reviewCount: 1234,
    stock: 999,
    deliveryType: 'local',
    description: '现点现煮，正宗柳州味',
    tags: ['螺蛳粉', '招牌', '必吃'],
  },
  {
    id: 6,
    name: '螺蛳粉礼盒装',
    nameEn: 'Luosifen Gift Box',
    category: 'luosifen',
    price: 68,
    originalPrice: 88,
    unit: '盒',
    imageUrl: 'https://i.imgur.com/LgCdOmj.jpeg',
    placeholderImage: '📦',
    seller: '柳州螺蛳粉集团',
    sellerId: 'seller_009',
    rating: 4.8,
    reviewCount: 567,
    stock: 1000,
    deliveryType: 'shipping',
    description: '送礼佳品，全国配送',
    tags: ['礼盒', '送礼', '全国配送'],
  },
  {
    id: 7,
    name: '螺蛳粉家庭装',
    nameEn: 'Family Pack Luosifen',
    category: 'luosifen',
    price: 128,
    originalPrice: 168,
    unit: '5包装',
    imageUrl: 'https://i.imgur.com/vy5fy6a.jpeg',
    placeholderImage: '🎁',
    seller: '柳州螺蛳粉集团',
    sellerId: 'seller_009',
    rating: 4.7,
    reviewCount: 234,
    stock: 2000,
    deliveryType: 'shipping',
    description: '家庭囤货装，超值优惠',
    tags: ['家庭装', '囤货', '超值'],
  },
  {
    id: 16,
    name: '干捞螺蛳粉',
    nameEn: 'Dry Luosifen',
    category: 'luosifen',
    price: 20,
    originalPrice: 28,
    unit: '碗',
    imageUrl: 'https://i.imgur.com/9Cctket.jpeg',
    placeholderImage: '🍝',
    seller: '青云螺蛳粉总店',
    sellerId: 'seller_008',
    rating: 4.8,
    reviewCount: 345,
    stock: 500,
    deliveryType: 'local',
    description: '干捞做法，味道更浓郁',
    tags: ['干捞', '螺蛳粉'],
  },
  {
    id: 17,
    name: '螺蛳鸭脚煲',
    nameEn: 'Luosifen Duck Feet Pot',
    category: 'luosifen',
    price: 48,
    originalPrice: 68,
    unit: '煲',
    imageUrl: 'https://i.imgur.com/qUiwHmH.jpeg',
    placeholderImage: '🍲',
    seller: '青云特色煲',
    sellerId: 'seller_010',
    rating: 4.9,
    reviewCount: 567,
    stock: 200,
    deliveryType: 'local',
    description: '螺蛳汤底，鸭脚软糯',
    tags: ['鸭脚煲', '螺蛳粉', '特色'],
  },

  // ========== 特产礼盒 (Gift Boxes) - 4 items ==========
  {
    id: 8,
    name: '柳州特产礼盒',
    nameEn: 'Liuzhou Gift Box',
    category: 'giftbox',
    price: 168,
    originalPrice: 228,
    unit: '盒',
    imageUrl: 'https://i.imgur.com/ystBRo2.jpeg',
    placeholderImage: '🎁',
    seller: '青云手信',
    sellerId: 'seller_011',
    rating: 4.9,
    reviewCount: 345,
    stock: 500,
    deliveryType: 'shipping',
    description: '螺蛳粉+云片糕+罗汉果茶组合',
    tags: ['礼盒', '送礼', '柳州特产'],
  },
  {
    id: 9,
    name: '青云夜市礼包',
    nameEn: 'Night Market Gift Pack',
    category: 'giftbox',
    price: 98,
    originalPrice: 128,
    unit: '袋',
    imageUrl: 'https://i.imgur.com/hV5LDeK.jpeg',
    placeholderImage: '🛍️',
    seller: '青云手信',
    sellerId: 'seller_011',
    rating: 4.6,
    reviewCount: 123,
    stock: 800,
    deliveryType: 'shipping',
    description: '夜市小吃精选组合',
    tags: ['小食', '夜市', '伴手礼'],
  },
  {
    id: 18,
    name: '柳州云片糕礼盒',
    nameEn: 'Liuzhou Cloud Cake Gift Box',
    category: 'giftbox',
    price: 58,
    originalPrice: 78,
    unit: '盒',
    imageUrl: 'https://i.imgur.com/vbpRKWz.jpeg',
    placeholderImage: '🍰',
    seller: '柳州老字号',
    sellerId: 'seller_012',
    rating: 4.5,
    reviewCount: 89,
    stock: 600,
    deliveryType: 'shipping',
    description: '传统云片糕，绵软香甜',
    tags: ['云片糕', '传统糕点', '伴手礼'],
  },
  {
    id: 24,
    name: '螺蛳粉超大礼包',
    nameEn: 'Luosifen Super Gift Pack',
    category: 'giftbox',
    price: 258,
    originalPrice: 328,
    unit: '盒',
    imageUrl: 'https://i.imgur.com/vbpRKWz.jpeg',
    placeholderImage: '🎁',
    seller: '柳州特产商城',
    sellerId: 'seller_013',
    rating: 4.9,
    reviewCount: 678,
    stock: 300,
    deliveryType: 'shipping',
    description: '10包装螺蛳粉+特产组合',
    tags: ['超大礼包', '螺蛳粉', '送礼'],
  },

  // ========== 特色饮品 (Drinks) - 5 items ==========
  {
    id: 10,
    name: '甘蔗汁',
    nameEn: 'Sugarcane Juice',
    category: 'drinks',
    price: 8,
    originalPrice: 12,
    unit: '杯',
    imageUrl: 'https://i.imgur.com/o2CSk8s.jpeg',
    placeholderImage: '🥤',
    seller: '青云饮品店',
    sellerId: 'seller_014',
    rating: 4.5,
    reviewCount: 89,
    stock: 999,
    deliveryType: 'local',
    description: '鲜榨甘蔗汁，清甜解渴',
    tags: ['饮品', '解渴', '鲜榨'],
  },
  {
    id: 11,
    name: '罗汉果茶',
    nameEn: 'Luohanguo Tea',
    category: 'drinks',
    price: 12,
    originalPrice: 18,
    unit: '瓶',
    imageUrl: 'https://i.imgur.com/ybIPQXm.jpeg',
    placeholderImage: '🍵',
    seller: '广西特产',
    sellerId: 'seller_015',
    rating: 4.7,
    reviewCount: 67,
    stock: 2000,
    deliveryType: 'shipping',
    description: '润肺止咳，广西特产',
    tags: ['养生', '茶饮', '特产'],
  },
  {
    id: 19,
    name: '酸梅汤',
    nameEn: 'Sour Plum Drink',
    category: 'drinks',
    price: 6,
    originalPrice: 10,
    unit: '杯',
    imageUrl: 'https://i.imgur.com/g6S8Yi6.jpeg',
    placeholderImage: '🥤',
    seller: '青云饮品店',
    sellerId: 'seller_014',
    rating: 4.6,
    reviewCount: 123,
    stock: 999,
    deliveryType: 'local',
    description: '自制酸梅汤，解腻开胃',
    tags: ['酸梅汤', '解暑', '传统'],
  },
  {
    id: 20,
    name: '玉米汁',
    nameEn: 'Corn Juice',
    category: 'drinks',
    price: 10,
    originalPrice: 15,
    unit: '杯',
    imageUrl: 'https://i.imgur.com/p4wEX3v.jpeg',
    placeholderImage: '🌽',
    seller: '青云饮品店',
    sellerId: 'seller_014',
    rating: 4.4,
    reviewCount: 56,
    stock: 999,
    deliveryType: 'local',
    description: '鲜榨玉米汁，香浓顺滑',
    tags: ['玉米汁', '健康饮品'],
  },
  {
    id: 25,
    name: '茅根竹蔗水',
    nameEn: 'Sugarcane & Herbal Drink',
    category: 'drinks',
    price: 10,
    originalPrice: 15,
    unit: '杯',
    imageUrl: 'https://i.imgur.com/1MbXg4U.jpeg',
    placeholderImage: '🌿',
    seller: '青云凉茶铺',
    sellerId: 'seller_016',
    rating: 4.7,
    reviewCount: 234,
    stock: 500,
    deliveryType: 'local',
    description: '清热解渴，传统凉茶',
    tags: ['凉茶', '清热', '传统'],
  },

  // ========== 外卖配送 (Delivery) - 5 items ==========
  {
    id: 12,
    name: '麻辣烫套餐',
    nameEn: 'Mala Tang Set',
    category: 'delivery',
    price: 35,
    originalPrice: 48,
    unit: '份',
    imageUrl: 'https://i.imgur.com/VljUFVz.jpeg',
    placeholderImage: '🍲',
    seller: '青云麻辣烫',
    sellerId: 'seller_017',
    rating: 4.6,
    reviewCount: 234,
    stock: 999,
    deliveryType: 'local',
    description: '自选麻辣烫，送米饭',
    tags: ['麻辣烫', '午餐', '外卖'],
  },
  {
    id: 13,
    name: '炒饭便当',
    nameEn: 'Fried Rice Bento',
    category: 'delivery',
    price: 22,
    originalPrice: 28,
    unit: '份',
    imageUrl: 'https://i.imgur.com/RIMIksQ.jpeg',
    placeholderImage: '🍚',
    seller: '青云快餐',
    sellerId: 'seller_018',
    rating: 4.4,
    reviewCount: 156,
    stock: 999,
    deliveryType: 'local',
    description: '特色炒饭+小菜+例汤',
    tags: ['便当', '快餐', '午餐'],
  },
  {
    id: 21,
    name: '黄焖鸡米饭',
    nameEn: 'Braised Chicken Rice',
    category: 'delivery',
    price: 28,
    originalPrice: 38,
    unit: '份',
    imageUrl: 'https://i.imgur.com/Z2WcKxF.jpeg',
    placeholderImage: '🍗',
    seller: '青云黄焖鸡',
    sellerId: 'seller_019',
    rating: 4.7,
    reviewCount: 234,
    stock: 500,
    deliveryType: 'local',
    description: '秘制黄焖鸡，配米饭',
    tags: ['黄焖鸡', '午餐', '外卖'],
  },
  {
    id: 22,
    name: '牛腩饭',
    nameEn: 'Beef Brisket Rice',
    category: 'delivery',
    price: 32,
    originalPrice: 42,
    unit: '份',
    imageUrl: 'https://i.imgur.com/QzSj9cI.jpeg',
    placeholderImage: '🥩',
    seller: '青云牛腩饭',
    sellerId: 'seller_020',
    rating: 4.8,
    reviewCount: 189,
    stock: 400,
    deliveryType: 'local',
    description: '慢炖牛腩，软烂入味',
    tags: ['牛腩饭', '午餐', '招牌'],
  },
  {
    id: 26,
    name: '叉烧饭',
    nameEn: 'BBQ Pork Rice',
    category: 'delivery',
    price: 26,
    originalPrice: 35,
    unit: '份',
    imageUrl: 'https://i.imgur.com/BocC3SG.jpeg',
    placeholderImage: '🍖',
    seller: '青云烧腊',
    sellerId: 'seller_021',
    rating: 4.6,
    reviewCount: 145,
    stock: 500,
    deliveryType: 'local',
    description: '蜜汁叉烧，配例汤',
    tags: ['叉烧饭', '烧腊', '午餐'],
  },
];

// Helper functions
export const getProductsByCategory = (categoryId) => {
  if (categoryId === 'all') return foodProducts;
  return foodProducts.filter((p) => p.category === categoryId);
};

export const getProductById = (id) => {
  return foodProducts.find((p) => p.id === id);
};

export const getProductsBySeller = (sellerId) => {
  return foodProducts.filter((p) => p.sellerId === sellerId);
};
